import {
  Product,
  Order,
  WingaAgent,
  UniversityLocation,
  BrandAsset,
  PayoutRequest,
  TradeInRequest,
  StoreSettings,
} from './types';
import { DEVELOPER_PROFILE_DEFAULTS, UNISOKO_CONTACT } from './siteConfig';

export const BRAND_ASSETS: BrandAsset[] = [
  {
    id: 'brand-logo-main',
    title: 'UniSoko Main Header Logo',
    path: '/icons/unisoko-logo.svg',
    category: 'logo',
    description: 'Electric Indigo badge with Emerald bolt and dual-color brand mark',
  },
  {
    id: 'brand-favicon',
    title: 'UniSoko App Favicon',
    path: '/favicon.svg',
    category: 'icon',
    description: 'Compact 32x32 rounded badge for browser tabs and mobile bookmarking',
  },
];

export const MBEYA_UNIVERSITIES: UniversityLocation[] = [
  {
    id: 'must',
    name: 'Mbeya University of Science and Technology',
    shortCode: 'MUST',
    city: 'Mbeya',
    campus: 'Main Campus (Iyunga)',
    isMbeya: true,
    region: 'Mbeya',
    popularSpots: [
      'Hostel Block A & B (New Hostels)',
      'Cafeteria Square',
      'Engineering Complex Landmark',
      'Main Gate Security Spot',
      'COET Labs Drop Point',
    ],
  },
  {
    id: 'teku',
    name: 'Teofilo Kisanji University',
    shortCode: 'TEKU',
    city: 'Mbeya',
    campus: 'Mbalizi Road Campus',
    isMbeya: true,
    region: 'Mbeya',
    popularSpots: [
      'Bishop Kisanji Memorial Hall',
      'St. John Hostel',
      'University Library Front',
      'TEKU Main Entrance',
    ],
  },
  {
    id: 'tia-mbeya',
    name: 'Tanzania Institute of Accountancy - Mbeya',
    shortCode: 'TIA Mbeya',
    city: 'Mbeya',
    campus: 'Mbeya Campus',
    isMbeya: true,
    region: 'Mbeya',
    popularSpots: [
      'Main Administration Block',
      'TIA Hostels Pavilion',
      'Student Center Canteen',
      'Gate 1 Pickup Spot',
    ],
  },
  {
    id: 'mzumbe-mbeya',
    name: 'Mzumbe University - Mbeya Campus College',
    shortCode: 'Mzumbe Mbeya',
    city: 'Mbeya',
    campus: 'Mzumbe Mbeya Campus',
    isMbeya: true,
    region: 'Mbeya',
    popularSpots: [
      'Faculty of Law Square',
      'Campus Library Landmark',
      'Executive Hostel',
      'Mzumbe Main Gate',
    ],
  },
  {
    id: 'cuom',
    name: 'Catholic University of Mbeya',
    shortCode: 'CUoM',
    city: 'Mbeya',
    campus: 'CUoM Mbeya Campus',
    isMbeya: true,
    region: 'Mbeya',
    popularSpots: [
      'St. Augustine Hall',
      'Main Quadrangle',
      'Women Hostel Gate',
      'Campus Administration Entrance',
    ],
  },
];

export const NON_MBEYA_UNIVERSITIES: UniversityLocation[] = [
  {
    id: 'udsm',
    name: 'University of Dar es Salaam',
    shortCode: 'UDSM',
    city: 'Dar es Salaam',
    campus: 'Mlimani Main Campus',
    isMbeya: false,
    region: 'Dar es Salaam',
    courierHub: 'Magufuli / Ubungo Bus Terminal (Kupitia BM Coach / Shabiby / Hood)',
    popularSpots: ['Hall 2 / Hall 5', 'Mabibo Hostels', 'Yombo Lecture Theatres', 'CoICT Kijitonyama'],
  },
  {
    id: 'udom',
    name: 'University of Dodoma',
    shortCode: 'UDOM',
    city: 'Dodoma',
    campus: 'UDOM Main Campus College',
    isMbeya: false,
    region: 'Dodoma',
    courierHub: 'Nanenane Bus Terminal (Kupitia BM Coach / Kimbinyiko / ABC Upper Class)',
    popularSpots: ['College of Informatics (CIVE)', 'College of Humanities (CHSS)', 'Benjamin Mkapa Hall'],
  },
  {
    id: 'sua',
    name: 'Sokoine University of Agriculture',
    shortCode: 'SUA',
    city: 'Morogoro',
    campus: 'Edward Moringe Campus',
    isMbeya: false,
    region: 'Morogoro',
    courierHub: 'Morogoro Msamvu Terminal (Kupitia New Force / Abood / Al Saedy)',
    popularSpots: ['Main Campus Hostels', 'Solomon Mahlangu Campus (Mazimbu)', 'Mazimbu Gate'],
  },
  {
    id: 'saut',
    name: 'St. Augustine University of Tanzania',
    shortCode: 'SAUT',
    city: 'Mwanza',
    campus: 'Nyegezi Main Campus',
    isMbeya: false,
    region: 'Mwanza',
    courierHub: 'Nyegezi Bus Stand (Kupitia Ally’s Star / Zuberi / Saratoga)',
    popularSpots: ['St. Thomas More Hostels', 'Campus Main Gate', 'Administration Block'],
  },
  {
    id: 'aru',
    name: 'Ardhi University',
    shortCode: 'ARU',
    city: 'Dar es Salaam',
    campus: 'Observation Hill Campus',
    isMbeya: false,
    region: 'Dar es Salaam',
    courierHub: 'Dar es Salaam central courier hub',
    popularSpots: ['Main Gate', 'Student Centre'],
  },
  {
    id: 'mzumbe-main',
    name: 'Mzumbe University',
    shortCode: 'MU',
    city: 'Morogoro',
    campus: 'Main Campus',
    isMbeya: false,
    region: 'Morogoro',
    courierHub: 'Morogoro central courier hub',
    popularSpots: ['Main Gate', 'Student Centre'],
  },
  {
    id: 'dit',
    name: 'Dar es Salaam Institute of Technology',
    shortCode: 'DIT',
    city: 'Dar es Salaam',
    campus: 'Main Campus',
    isMbeya: false,
    region: 'Dar es Salaam',
    courierHub: 'Dar es Salaam central courier hub',
    popularSpots: ['Main Gate', 'Student Centre'],
  },
  {
    id: 'ifm',
    name: 'Institute of Finance Management',
    shortCode: 'IFM',
    city: 'Dar es Salaam',
    campus: 'Main Campus',
    isMbeya: false,
    region: 'Dar es Salaam',
    courierHub: 'Dar es Salaam central courier hub',
    popularSpots: ['Main Gate', 'Student Centre'],
  },
];

export const OTHER_TANZANIA_UNIVERSITY: UniversityLocation = {
  id: 'other-tanzania',
  name: 'Other University (Tanzania)',
  shortCode: 'OTHER',
  city: 'Tanzania',
  campus: 'Enter your university name',
  isMbeya: false,
  region: 'Tanzania',
  courierHub: 'Regional courier hub (confirm with UniSoko operations)',
  popularSpots: [],
};

export const ALL_UNIVERSITIES: UniversityLocation[] = [
  ...MBEYA_UNIVERSITIES,
  ...NON_MBEYA_UNIVERSITIES,
  OTHER_TANZANIA_UNIVERSITY,
];

// University institutions on the TCU approved list (March 2026). The current
// store campuses above remain included for the locations UniSoko already serves.
const TCU_UNIVERSITY_INSTITUTIONS = [
  'Open University of Tanzania (OUT)',
  'State University of Zanzibar (SUZA)',
  'Nelson Mandela African Institution of Science and Technology (NM-AIST)',
  'Muhimbili University of Health and Allied Sciences (MUHAS)',
  'Moshi Cooperative University (MoCU)',
  'Mwalimu Nyerere University of Agriculture and Technology (MNUAT)',
  'Kairuki University (KU)',
  'Abdulrahman Al-Sumait University (SUMAIT)',
  'Zanzibar University (ZU)',
  'Tumaini University Makumira (TUMA)',
  'Aga Khan University (AKU)',
  'Catholic University of Health and Allied Sciences (CUHAS)',
  'University of Arusha (UoA)',
  'St. Joseph University in Tanzania (SJUIT)',
  'Mwenge Catholic University (MWECAU)',
  'Muslim University of Morogoro (MUM)',
  'University of Iringa (UoI)',
  "St. John's University of Tanzania (SJUT)",
  'Kampala International University in Tanzania (KIUT)',
  'United African University of Tanzania (UAUT)',
  'Ruaha Catholic University (RUCU)',
  'Mwanza University (MzU)',
  'Dar es Salaam Tumaini University (DarTU)',
  'Rabininsia University (RU)',
  'University of Medical Sciences and Technology (UMST)',
  'Hikmah University of East Africa (HUEA)',
  'KCMC University',
  'Dar es Salaam University College of Education (DUCE)',
  'Mkwawa University College of Education (MUCE)',
  'Mzumbe University – Dar es Salaam Campus College',
  'Mbeya College of Health and Allied Sciences (MCHAS)',
  'Mbeya University of Science and Technology – Rukwa Campus College',
  'Sokoine University of Agriculture – Mizengo Pinda Campus College',
  'Mbeya University of Science and Technology – Mtwara Campus College of Technical Education',
  'Stefano Moshi Memorial University College (SMMUCo)',
  'Archbishop Mihayo University College of Tabora (AMUCTA)',
  'Jordan University College (JUCo)',
  'St. Francis University College of Health and Allied Sciences (SFUCHAS)',
  'Stella Maris Mtwara University College (STeMMUCo)',
  'Marian University College (MARUCo)',
  'St. Joseph University College of Health and Allied Sciences (SJCHAS)',
  'Mwenge Catholic University – Hedaru Campus College (MWECAU-HCC)',
];

export const CAMPUS_EXPANSION_UNIVERSITIES = [
  ...ALL_UNIVERSITIES.map((university) => ({
    id: university.id,
    name: university.name,
    campus: university.campus,
    region: university.region,
  })),
  ...TCU_UNIVERSITY_INSTITUTIONS.map((name) => ({
    id: `tcu-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    name,
    campus: 'Main institution',
    region: 'Tanzania',
  })),
];

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  merchantName: 'UniSoko Marketplace TZ',
  accountName: 'UNISOKO TECH CAMPUS HUB',
  tillNumber: '5849201',
  supportPhone: UNISOKO_CONTACT.phoneDisplay,
  supportWhatsApp: UNISOKO_CONTACT.whatsappUrl,
  minPayoutThreshold: 20000,
  bannerNotice: 'Semester Rush: Group wholesale discounts unlock automatically at 3+ units on all gadgets!',
  paymentMethods: [
    { id: 'mpesa-primary', network: 'M-Pesa', tillNumber: '5849201', accountName: 'UNISOKO TECH CAMPUS HUB', enabled: true },
    { id: 'tigo-primary', network: 'Tigo Pesa', tillNumber: '', accountName: '', enabled: true },
    { id: 'airtel-primary', network: 'Airtel Money', tillNumber: '', accountName: '', enabled: true },
  ],
  officialWhatsAppNumbers: [UNISOKO_CONTACT.phoneDigits],
  developerProfile: { ...DEVELOPER_PROFILE_DEFAULTS },
  partnerBadges: [
    { name: 'Mbeya University of Science & Technology', shortCode: 'MUST', category: 'Campus Partner' },
    { name: 'Teofilo Kisanji University', shortCode: 'TEKU', category: 'Campus Partner' },
    { name: 'Tanzania Institute of Accountancy', shortCode: 'TIA Mbeya', category: 'Campus Partner' },
    { name: 'Vodacom M-Pesa / Lipa Namba', shortCode: 'M-PESA', category: 'Payment Partner' },
    { name: 'AzamPesa Tanzania', shortCode: 'AZAMPAY', category: 'Payment Partner' },
  ],
};

export const LIPA_NAMBA_DETAILS = {
  tillNumber: '5849201',
  accountName: 'UNISOKO TECH CAMPUS HUB',
  merchantName: 'UniSoko Marketplace TZ',
  networks: ['M-Pesa (Vodacom)', 'Tigo Pesa (Mix by Yas)', 'Airtel Money', 'Halopesa', 'AzamPesa'],
  ussdShortcuts: [
    { network: 'Vodacom M-Pesa', ussd: '*150*00# > Lipa kwa M-Pesa > Weka Lipa Namba (5849201)' },
    { network: 'Tigo Pesa', ussd: '*150*01# > Lipa kwa Simu > Weka Namba ya Muuzaji (5849201)' },
    { network: 'Airtel Money', ussd: '*150*60# > Lipa kwa Airtel Money > Weka Lipa Namba (5849201)' },
  ],
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-hp-elitebook-840-g6',
    title: 'HP EliteBook 840 G6 (Core i5 8th Gen, 16GB RAM, 256GB NVMe SSD)',
    description:
      'Ultra-durable aluminum enterprise laptop built for coursework, programming, and multitasking. Features a 14-inch Full HD anti-glare display, backlit keyboard, Bang & Olufsen tuned audio, and all-day battery performance.',
    category: 'Laptops',
    brand: 'HP',
    model: 'EliteBook 840 G6',
    priceRetail: 650000,
    priceWholesale: 580000,
    condition: 'Grade A Like-New',
    stockStatus: 'In Stock',
    featured: true,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      processor: 'Intel Core i5-8365U',
      ram: '16GB DDR4',
      storage: '256GB PCIe NVMe SSD',
      display: '14-inch FHD IPS anti-glare',
      battery: 'Up to 7 hours (listing estimate)',
      details: { Ports: 'Thunderbolt 3 USB-C, 2x USB 3.1, HDMI, RJ-45 LAN' },
    },
    specs: {
      Processor: 'Intel Core i5-8365U (Quad-Core up to 4.1GHz)',
      Memory: '16GB DDR4 RAM',
      Storage: '256GB PCIe NVMe M.2 SSD',
      Display: '14.0" FHD (1920 x 1080) IPS Anti-Glare',
      Battery: 'Up to 7 hours battery health',
      Ports: 'Thunderbolt 3 USB-C, 2x USB 3.1, HDMI, RJ-45 LAN',
    },
  },
  {
    id: 'prod-room-desk-lamp',
    title: 'Adjustable LED Student Desk Lamp with USB Port',
    description: 'A compact, dimmable study lamp with flexible positioning for late-night reading and charging essentials.',
    category: 'Room Gear',
    priceRetail: 45000,
    priceWholesale: 39000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80'],
    specs: { Lighting: 'Dimmable LED', Power: 'USB powered', Use: 'Dorm desk / bedside' },
  },
  {
    id: 'prod-room-fan',
    title: 'Portable Quiet Desk Fan for Dorm Rooms',
    description: 'A rechargeable compact fan with quiet operation and adjustable airflow for study desks and small rooms.',
    category: 'Room Gear',
    priceRetail: 65000,
    priceWholesale: 57000,
    condition: 'Brand New',
    stockStatus: 'New Stock',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1618941716939-553df3c6c278?auto=format&fit=crop&w=800&q=80'],
    specs: { Type: 'Rechargeable desk fan', Speed: 'Multiple settings', Use: 'Dorm / study room' },
  },
  {
    id: 'prod-room-mattress',
    title: 'Single Student Mattress with Washable Cover',
    description: 'A supportive single-bed mattress in a dorm-friendly size, with a removable washable cover.',
    category: 'Room Gear',
    priceRetail: 180000,
    priceWholesale: 165000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80'],
    specs: { Size: 'Single', Cover: 'Removable / washable', Use: 'Dormitory room' },
  },
  {
    id: 'prod-accessory-ring-light',
    title: 'Compact Phone Ring Light & Desk Tripod',
    description: 'Portable ring light and adjustable phone stand for video calls, content creation, and online classes.',
    category: 'Smart Phones & Accessories',
    priceRetail: 38000,
    priceWholesale: 32000,
    condition: 'Brand New',
    stockStatus: 'Trending',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=800&q=80'],
    specs: { Lighting: 'Multiple brightness levels', Mount: 'Adjustable phone holder', Power: 'USB' },
  },
  {
    id: 'prod-dell-latitude-7400',
    title: 'Dell Latitude 7400 Carbon Fiber (Core i7 8th Gen, 16GB RAM, 512GB SSD)',
    description:
      'Premium lightweight business powerhouse. Featuring carbon fiber lid construction, ExpressCharge battery technology, crisp narrow-border FHD screen, and fingerprint authentication for engineering and accounting students.',
    category: 'Laptops',
    brand: 'Dell',
    model: 'Latitude 7400',
    priceRetail: 780000,
    priceWholesale: 710000,
    condition: 'Grade A Like-New',
    stockStatus: 'Trending',
    featured: true,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      processor: 'Intel Core i7-8665U',
      ram: '16GB DDR4',
      storage: '512GB NVMe SSD',
      display: '14-inch FHD WVA (touch options vary)',
      details: { Weight: '1.35 kg' },
    },
    specs: {
      Processor: 'Intel Core i7-8665U (up to 4.8GHz Turbo)',
      Memory: '16GB DDR4 High-Speed RAM',
      Storage: '512GB NVMe Solid State Drive',
      Display: '14.0" FHD WVA Touch/Non-Touch options',
      Weight: '1.35 kg ultra-portable',
    },
  },
  {
    id: 'prod-macbook-pro-m1',
    title: 'Apple MacBook Pro 13" (Apple M1 Chip, 8GB Unified Memory, 256GB SSD)',
    description:
      'Incredible performance with blazing-fast Apple Silicon M1. Unbelievable 20-hour battery life, brilliant Retina display with True Tone, studio-quality mics, and active cooling for video editing, software engineering, and graphic design.',
    category: 'Laptops',
    brand: 'Apple',
    model: 'MacBook Pro 13-inch (M1)',
    priceRetail: 1850000,
    priceWholesale: 1720000,
    condition: 'Refurbished',
    stockStatus: 'Trending',
    featured: true,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      processor: 'Apple M1 (8-core CPU, 8-core GPU)',
      ram: '8GB unified memory',
      storage: '256GB SSD',
      display: '13.3-inch Retina',
      battery: 'Up to 20 hours (manufacturer estimate)',
      details: { Security: 'Touch ID' },
    },
    specs: {
      Chip: 'Apple M1 (8-core CPU, 8-core GPU, 16-core Neural Engine)',
      Memory: '8GB Unified Memory',
      Storage: '256GB Superfast SSD',
      Screen: '13.3" Retina Display with P3 Wide Color (500 nits)',
      Security: 'Touch ID Sensor',
    },
  },
  {
    id: 'prod-iphone-13-128gb',
    title: 'Apple iPhone 13 128GB (Midnight Blue / Starlight)',
    description:
      'Super Retina XDR OLED display, advanced dual-camera system with Cinematic Mode, A15 Bionic lightning-fast processor, 5G cellular speed, Ceramic Shield front glass, and all-day battery reliability.',
    category: 'Phones',
    brand: 'Apple',
    model: 'iPhone 13',
    priceRetail: 1250000,
    priceWholesale: 1150000,
    condition: 'Refurbished',
    stockStatus: 'New Stock',
    featured: true,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      processor: 'Apple A15 Bionic',
      storage: '128GB',
      display: '6.1-inch Super Retina XDR OLED',
      battery: 'Battery health varies by unit; confirm with UniSoko before purchase',
      connectivity: '5G, nano-SIM + eSIM',
      details: { Camera: 'Dual 12MP wide and ultra-wide' },
    },
    specs: {
      Display: '6.1" Super Retina XDR OLED',
      Processor: 'Apple A15 Bionic (6-core CPU)',
      Camera: 'Dual 12MP Wide and Ultra-Wide with Sensor-shift OIS',
      Battery: '100% / 90%+ Battery Health Guarantee',
      Network: 'Factory Unlocked, Dual SIM (nano-SIM + eSIM)',
    },
  },
  {
    id: 'prod-samsung-galaxy-a54',
    title: 'Samsung Galaxy A54 5G 128GB / 8GB RAM (Awesome Graphite)',
    description:
      'Vivid 120Hz Super AMOLED screen, 50MP triple OIS camera system, IP67 water and dust resistance, and 5000mAh battery that easily powers through 2 days of campus lectures and social media.',
    category: 'Phones',
    brand: 'Samsung',
    model: 'Galaxy A54 5G',
    priceRetail: 720000,
    priceWholesale: 645000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    featured: false,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      ram: '8GB',
      storage: '128GB (microSD expandable)',
      display: '6.4-inch FHD+ 120Hz Super AMOLED',
      battery: '5,000mAh',
      connectivity: '5G',
      details: { Protection: 'Gorilla Glass 5, IP67' },
    },
    specs: {
      Display: '6.4" FHD+ 120Hz Super AMOLED (1000 nits)',
      RAM_Storage: '8GB RAM + 128GB Storage (MicroSD expandable up to 1TB)',
      Battery: '5,000 mAh with 25W Fast Charging',
      Protection: 'Gorilla Glass 5 & IP67 Water Resistance',
    },
  },
  {
    id: 'prod-soundcore-space-one',
    title: 'Anker Soundcore Space One Wireless ANC Headphones',
    description:
      'Active Noise Cancelling headphones custom built for campus library study sessions and hostel focus. Features 2x stronger voice reduction, 55 hours playtime, Hi-Res Audio wireless LDAC, and ultra-plush memory foam earcups.',
    category: 'Power & Audio',
    priceRetail: 210000,
    priceWholesale: 175000,
    condition: 'Brand New',
    stockStatus: 'New Stock',
    featured: false,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
    specs: {
      Battery: '55 Hours (ANC off) / 40 Hours (ANC on)',
      Audio: '40mm customized dynamic drivers with Hi-Res LDAC',
      Connectivity: 'Bluetooth 5.3 + Multi-point connection',
      FastCharge: '5 min charge = 4 hours playback',
    },
  },
  {
    id: 'prod-gan-65w-charger',
    title: 'Baseus 65W GaN5 Pro Fast Charger + 100W Type-C Cable',
    description:
      'High-speed Gallium Nitride 3-port wall charger capable of charging your laptop, phone, and tablet simultaneously. Compact, foldable pins, and built-in surge protection.',
    category: 'Accessories',
    priceRetail: 75000,
    priceWholesale: 58000,
    condition: 'Brand New',
    stockStatus: 'Trending',
    featured: true,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
    specs: {
      Output: '65W Max (2x USB-C + 1x USB-A)',
      Protocol: 'PD 3.0, QC 4.0+, PPS, SCP',
      Cable: 'Included 100W 1.2m E-marker Braided Cable',
    },
  },
  {
    id: 'prod-usbc-hub-10in1',
    title: 'Ugreen 10-in-1 Aluminum USB-C Hub (4K HDMI, Gigabit LAN, SD/TF)',
    description:
      'Essential adapter for student MacBook and ultrabook users. Connect external library monitors, projectors for presentations, ethernet LAN cables, and SD cards with zero lag.',
    category: 'Accessories',
    priceRetail: 95000,
    priceWholesale: 78000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    featured: false,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=80',
    ],
    specs: {
      Ports: '4K@60Hz HDMI, 1000Mbps RJ45 LAN, 100W PD Pass-through, 3x USB 3.0',
      Material: 'Heat-dissipating space gray aluminum alloy',
    },
  },
  {
    id: 'prod-powerbank-20000mah',
    title: 'Oraimo 20,000mAh PowerPro 22.5W Fast Charge Power Bank',
    description:
      'Massive capacity dual-output backup battery. Keeps your smartphone and study accessories powered during campus power outages or whole-day lecture shifts.',
    category: 'Campus Essentials',
    priceRetail: 65000,
    priceWholesale: 52000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    featured: false,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1609592424388-e2eb7fa444b0?auto=format&fit=crop&w=800&q=80',
    ],
    specs: {
      Capacity: '20,000mAh (74Wh airline-safe)',
      Speed: '22.5W Super Charge / 20W PD Type-C Two-way',
      LED: 'Digital battery percentage screen',
    },
  },
  {
    id: 'prod-studio-ringlight-10inch',
    title: '10" LED Multi-Color Studio Ring Light + 1.6m Metal Tripod',
    description:
      'Built for student content creators, online presentations, Zoom class meetings, and TikTok live streaming. Comes with 3 color modes and Bluetooth remote shutter.',
    category: 'Campus Essentials',
    priceRetail: 48000,
    priceWholesale: 38000,
    condition: 'Brand New',
    stockStatus: 'New Stock',
    featured: false,
    minWholesaleQty: 3,
    images: [
      'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=800&q=80',
    ],
    specs: {
      Lighting: 'Warm, Cool, Natural daylight with 10 brightness levels',
      Power: 'USB 5V powered via laptop or power bank',
      Tripod: 'Reinforced 160cm adjustable aluminum stand',
    },
  },
  {
    id: 'prod-room-bedframe',
    title: 'Compact Single Student Bed Frame',
    description: 'A sturdy, space-conscious single bed frame suited to student rooms and hostel spaces.',
    category: 'Room Gear',
    priceRetail: 320000,
    priceWholesale: 285000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80'],
    specs: { Size: 'Single', Assembly: 'Flat-pack', Use: 'Student room' },
  },
  {
    id: 'prod-laptop-stand',
    title: 'Adjustable Aluminum Laptop Stand',
    description: 'An adjustable, foldable stand for better screen height and airflow during study sessions.',
    category: 'Accessories',
    priceRetail: 48000,
    priceWholesale: 40000,
    condition: 'Brand New',
    stockStatus: 'In Stock',
    minWholesaleQty: 3,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80'],
    specs: { Material: 'Aluminum alloy', Design: 'Foldable, adjustable height', Compatibility: 'Most laptops and tablets' },
  },
];

export const MOCK_WINGA_AGENTS: WingaAgent[] = [
  {
    id: 'winga-001',
    fullName: 'Samwel Mwambene',
    phone: '+255 754 892 110',
    university: 'MUST (Mbeya University of Science and Technology)',
    joinedAt: '2025-09-12T10:00:00.000Z',
    promoCode: 'WINGA-SAM',
    totalEarnings: 485000,
    pendingBalance: 65000,
    availableBalance: 140000,
    paidOut: 280000,
    commissionRate: 0.05,
    salesCount: 19,
    studentIdCardUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    kycStatus: 'Verified',
  },
  {
    id: 'winga-002',
    fullName: 'Mary Mwakipesile',
    phone: '+255 768 341 905',
    university: 'TIA Mbeya (Tanzania Institute of Accountancy)',
    joinedAt: '2025-10-06T10:00:00.000Z',
    promoCode: 'WINGA-MARY',
    totalEarnings: 390000,
    pendingBalance: 45000,
    availableBalance: 95000,
    paidOut: 250000,
    commissionRate: 0.05,
    salesCount: 14,
    studentIdCardUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    kycStatus: 'Verified',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-TZ-2026-0081',
    productId: 'prod-hp-elitebook-840-g6',
    buyerName: 'Kelvin Josephat',
    buyerPhone: '+255 712 345 678',
    university: 'MUST',
    deliverySpotType: 'Hostel',
    deliveryDetails: 'Hostel Block B, Room 214 (Iyunga Campus)',
    quantity: 1,
    totalAmount: 650000,
    wingaCodeUsed: 'WINGA-SAM',
    lipaNambaTxId: 'MP789123849',
    status: 'Approved',
    createdAt: '2026-09-28T14:32:00Z',
  },
  {
    id: 'ORD-TZ-2026-0082',
    productId: 'prod-soundcore-space-one',
    buyerName: 'Amina Salum',
    buyerPhone: '+255 744 987 654',
    university: 'TIA Mbeya',
    deliverySpotType: 'Landmark',
    deliveryDetails: 'Campus Cafeteria Entrance (Main Bench)',
    quantity: 3,
    totalAmount: 525000, // Wholesale rate 175,000 * 3
    wingaCodeUsed: 'WINGA-MARY',
    lipaNambaTxId: 'AZ552109483',
    status: 'Out for Delivery',
    createdAt: '2026-09-29T08:15:00Z',
  },
  {
    id: 'ORD-TZ-2026-0083',
    productId: 'prod-dell-latitude-7400',
    buyerName: 'Baraka Emmanuel',
    buyerPhone: '+255 789 221 340',
    university: 'Mzumbe Mbeya',
    deliverySpotType: 'Hostel',
    deliveryDetails: 'Executive Hostel, Room 12',
    quantity: 1,
    totalAmount: 780000,
    wingaCodeUsed: 'WINGA-SAM',
    lipaNambaTxId: 'MP900145271',
    status: 'Pending Verification',
    createdAt: '2026-09-29T09:40:00Z',
  },
];

export const MOCK_PAYOUTS: PayoutRequest[] = [
  {
    id: 'PAY-2026-0041',
    agentId: 'winga-001',
    agentName: 'Samwel Mwambene',
    promoCode: 'WINGA-SAM',
    phone: '+255 754 892 110',
    university: 'MUST (Mbeya University of Science and Technology)',
    amount: 50000,
    status: 'Pending',
    requestedAt: '2026-09-29T08:30:00Z',
    kycStatus: 'Verified',
  },
  {
    id: 'PAY-2026-0040',
    agentId: 'winga-002',
    agentName: 'Mary Mwakipesile',
    promoCode: 'WINGA-MARY',
    phone: '+255 768 341 905',
    university: 'TIA Mbeya (Tanzania Institute of Accountancy)',
    amount: 45000,
    status: 'Paid',
    requestedAt: '2026-09-28T10:15:00Z',
    paidAt: '2026-09-28T14:20:00Z',
    b2cReferenceId: 'MPB2C89210491',
    kycStatus: 'Verified',
  },
];

export const MOCK_TRADE_IN_REQUESTS: TradeInRequest[] = [
  {
    id: 'TRD-2026-0012',
    studentName: 'Geoffrey Mwashiuya',
    phone: '+255 744 112 890',
    university: 'MUST (Mbeya University of Science and Technology)',
    itemTitle: 'Lenovo ThinkPad T480 (Core i5 8th Gen, 8GB RAM, 256GB SSD)',
    category: 'Laptops',
    condition: 'Like-New (Grade A)',
    specs: 'Intel Core i5-8250U, dual battery working fine (6h+), original charger included.',
    expectedPrice: 480000,
    offeredPrice: 440000,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    status: 'Pending Review',
    adminNotes: 'Candidate for quick inspection at Iyunga main gate.',
    submittedAt: '2026-09-29T09:10:00Z',
  },
  {
    id: 'TRD-2026-0011',
    studentName: 'Brenda Mwakisole',
    phone: '+255 765 443 219',
    university: 'TEKU (Teofilo Kisanji University)',
    itemTitle: 'iPhone 11 64GB Purple (Battery Health 84%)',
    category: 'Phones',
    condition: 'Gently Used (Grade B)',
    specs: 'Screen clean with tempered glass, minor scratches on outer frame, FaceID and cameras 100% functional.',
    expectedPrice: 420000,
    offeredPrice: 390000,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    status: 'Offer Made',
    adminNotes: 'Offered 390,000 TZS. Student to confirm pickup at TEKU library.',
    submittedAt: '2026-09-28T16:40:00Z',
  },
];

/**
 * Currency and Pricing Helpers
 */
export function formatTZS(amount: number): string {
  return `TZS ${new Intl.NumberFormat('en-TZ', {
    maximumFractionDigits: 0,
  }).format(amount)}`;
}

export function calculateWholesaleSavings(
  retailPrice: number,
  wholesalePrice: number,
  quantity: number = 3
): { totalSavings: number; percentSaved: number } {
  const retailTotal = retailPrice * quantity;
  const wholesaleTotal = wholesalePrice * quantity;
  const totalSavings = Math.max(0, retailTotal - wholesaleTotal);
  const percentSaved = retailTotal > 0 ? Math.round((totalSavings / retailTotal) * 100) : 0;

  return { totalSavings, percentSaved };
}
