'use client';

import { useCallback, useEffect, useState } from 'react';

type AdminPlan = { id: string; name: string; description: string; price: number; currency: string; duration_days: number; product_limit: number | null; is_popular: boolean; is_active: boolean };
type PaymentMethod = { id: string; name: string; instructions: string; public_details: Record<string, unknown>; is_active: boolean };
type Payment = { id: string; amount: number; currency: string; transaction_reference: string | null; status: string; submitted_at: string; payment_method_snapshot: Record<string, unknown>; subscriptions: { plan_snapshot: Record<string, unknown>; seller_profiles: { display_name: string; university: string } } };

export default function AdminSubscriptions() {
  const [plans, setPlans] = useState<AdminPlan[]>([]);
  const [methods, setMethods] = useState<PaymentMethod[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [trialDays, setTrialDays] = useState(30);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const response = await fetch('/api/admin/subscription-payments', { cache: 'no-store' });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error || 'Could not load plans.');
    setPlans(result.plans || []); setMethods(result.paymentMethods || []); setPayments(result.payments || []); setTrialDays(result.trialDurationDays || 30);
  }, []);
  useEffect(() => { void Promise.resolve().then(load).catch((err: unknown) => setError(err instanceof Error ? err.message : 'Could not load plans.')); }, [load]);
  const save = async (body: Record<string, unknown>) => {
    setBusy(true); setError('');
    try { const response = await fetch('/api/admin/subscription-payments', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not save.'); await load(); }
    catch (err) { setError(err instanceof Error ? err.message : 'Could not save.'); }
    finally { setBusy(false); }
  };
  return <main className="mx-auto max-w-6xl space-y-8 px-4 py-8 sm:px-6">
    <header><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Seller subscriptions</p><h1 className="mt-1 text-2xl font-black">Plans and payment review</h1></header>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <form onSubmit={(event) => { event.preventDefault(); void save({ action: 'update_trial_duration', days: trialDays }); }} className="flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><label className="text-sm font-bold">New seller trial duration (days)<input type="number" min="1" max="365" value={trialDays} onChange={(event) => setTrialDays(Number(event.target.value))} className="ml-3 w-24 rounded-lg border p-2 text-sm dark:bg-slate-950"/></label><button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Save trial</button><p className="basis-full text-xs text-slate-500">Applies to new trials. Existing trial end dates do not change.</p></form>
    <section className="space-y-3"><h2 className="text-lg font-bold">Paid plans</h2>{plans.filter((plan) => plan.price > 0).map((plan) => <form key={plan.id} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void save({ action: 'update_plan', id: plan.id, name: form.get('name'), description: form.get('description'), price: form.get('price'), durationDays: form.get('durationDays'), productLimit: form.get('productLimit') || null, isPopular: form.get('isPopular') === 'on', isActive: form.get('isActive') === 'on' }); }} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-6"><input name="name" defaultValue={plan.name} aria-label="Plan name" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><input name="price" type="number" min="0" defaultValue={plan.price} aria-label="Price in TZS" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><input name="durationDays" type="number" min="1" defaultValue={plan.duration_days} aria-label="Duration in days" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><input name="productLimit" type="number" min="0" defaultValue={plan.product_limit ?? ''} placeholder="Unlimited" aria-label="Product limit" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><input name="description" defaultValue={plan.description} aria-label="Plan description" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><div className="flex items-center gap-3 text-xs"><label><input name="isPopular" type="checkbox" defaultChecked={plan.is_popular}/> Popular</label><label><input name="isActive" type="checkbox" defaultChecked={plan.is_active}/> Active</label><button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 font-bold text-white">Save</button></div></form>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-bold">Payment instructions</h2>{methods.map((method) => <form key={method.id} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); let publicDetails: Record<string, unknown> = {}; try { publicDetails = JSON.parse(String(form.get('publicDetails') || '{}')); } catch { setError('Public details must be valid JSON.'); return; } void save({ action: 'update_payment_method', id: method.id, name: form.get('name'), instructions: form.get('instructions'), publicDetails, isActive: form.get('isActive') === 'on' }); }} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-3"><input name="name" defaultValue={method.name} aria-label="Payment method name" className="rounded-lg border p-2 text-sm dark:bg-slate-950"/><label className="text-sm"><input name="isActive" type="checkbox" defaultChecked={method.is_active}/> Active</label></div><textarea name="instructions" defaultValue={method.instructions} aria-label="Payment instructions" className="min-h-20 rounded-lg border p-2 text-sm dark:bg-slate-950"/><textarea name="publicDetails" defaultValue={JSON.stringify(method.public_details, null, 2)} aria-label="Public payment details JSON" className="min-h-20 rounded-lg border p-2 font-mono text-xs dark:bg-slate-950"/><button disabled={busy} className="w-fit rounded-lg bg-indigo-600 px-3 py-2 text-sm font-bold text-white">Save payment method</button></form>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-bold">Payment submissions</h2>{payments.length === 0 && <p className="text-sm text-slate-500">No payment submissions yet.</p>}{payments.map((payment) => <article key={payment.id} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{payment.subscriptions.seller_profiles.display_name} · {String(payment.subscriptions.plan_snapshot.name || 'Paid plan')}</p><p className="text-sm text-slate-600">{payment.subscriptions.seller_profiles.university} · {payment.currency} {Number(payment.amount).toLocaleString()} · Ref: {payment.transaction_reference || 'Not supplied'} · {new Date(payment.submitted_at).toLocaleString()}</p><p className="mt-1 text-xs capitalize">Status: {payment.status}</p></div>{payment.status === 'pending' && <div className="flex items-start gap-2"><button disabled={busy} onClick={() => void save({ id: payment.id, action: 'approve' })} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve</button><button disabled={busy} onClick={() => { const reason = window.prompt('Reason for rejection?'); if (reason) void save({ id: payment.id, action: 'reject', reason }); }} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white">Reject</button></div>}</div></article>)}</section>
  </main>;
}
