'use client';

import { useCallback, useEffect, useState } from 'react';
import { formatTZS } from '@/lib/mockData';

type Commission = { id: string; order_id: string; product_title: string; commission_rate: number; commission_base: number; amount: number; status: string; created_at: string; payout_reference: string | null; winga: { full_name: string; email: string; promo_code: string }; seller: { display_name: string } | null };
export default function AdminWingaCommissions() {
  const [rows, setRows] = useState<Commission[]>([]);
  const [references, setReferences] = useState<Record<string, string>>({});
  const [error, setError] = useState('');
  const [busy, setBusy] = useState('');
  const load = useCallback(async () => { const response = await fetch('/api/admin/winga-commissions', { cache: 'no-store' }); const result = await response.json() as { commissions?: Commission[]; error?: string }; if (!response.ok) throw new Error(result.error || 'Could not load commissions.'); setRows(result.commissions || []); }, []);
  useEffect(() => { void Promise.resolve().then(load).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load commissions.')); }, [load]);
  const markPaid = async (row: Commission) => { const reference = references[row.id]?.trim(); if (!reference) { setError('Enter the external payout reference before marking a commission paid.'); return; } setBusy(row.id); setError(''); try { const response = await fetch('/api/admin/winga-commissions', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: row.id, reference }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || 'Could not update payout status.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update payout status.'); } finally { setBusy(''); } };
  const payable = rows.filter((row) => row.status === 'payable').reduce((sum, row) => sum + Number(row.amount), 0);
  return <main className="mx-auto max-w-6xl space-y-5 px-4 py-8 sm:px-6"><header><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Winga programme</p><h1 className="mt-1 text-2xl font-black">Commission settlement</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Payable commissions are created after verified payment and delivery. Transfer the money through the configured provider before recording its reference here.</p></header>{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<section className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-500">Current payable balance</p><p className="mt-1 text-2xl font-black">{formatTZS(payable)}</p></section><section className="space-y-3">{rows.map((row) => <article key={row.id} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">{row.winga?.full_name || 'Winga'} · {row.product_title}</h2><p className="mt-1 text-xs text-slate-500">{row.winga?.promo_code} · {row.seller?.display_name || 'UniSoko product'} · Order {row.order_id}</p><p className="mt-1 text-xs text-slate-500">{(Number(row.commission_rate) * 100).toFixed(1)}% of {formatTZS(Number(row.commission_base))} · {new Date(row.created_at).toLocaleString()}</p></div><div className="text-right"><p className="font-black">{formatTZS(Number(row.amount))}</p><p className="text-xs capitalize text-slate-500">{row.status}</p></div></div>{row.status === 'payable' ? <div className="mt-3 flex flex-wrap gap-2"><input aria-label="External payout reference" placeholder="External payout reference" value={references[row.id] || ''} onChange={(e) => setReferences({ ...references, [row.id]: e.target.value })} className="min-h-10 min-w-64 flex-1 rounded-lg border px-3 text-xs dark:bg-slate-950"/><button disabled={busy === row.id} onClick={() => void markPaid(row)} className="min-h-10 rounded-lg bg-emerald-700 px-4 text-xs font-bold text-white disabled:opacity-50">{busy === row.id ? 'Saving…' : 'Record payout'}</button></div> : row.payout_reference && <p className="mt-3 text-xs text-emerald-700">Payout reference: {row.payout_reference}</p>}</article>)}{rows.length === 0 && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">No commission records yet.</p>}</section></main>;
}
