'use client';

import { useCallback, useEffect, useState } from 'react';

type Row = Record<string, unknown> & { id: string };
type State = { catalog: Record<string, Row[]>; verifications: Row[]; reports: Row[]; analytics: Record<string, unknown>; audit: Row[] };
const blank: State = { catalog: { categories: [], subcategories: [], conditions: [], attributes: [], options: [] }, verifications: [], reports: [], analytics: {}, audit: [] };
const tabs = ['Overview', 'Categories', 'Subcategories', 'Conditions', 'Attributes', 'Verifications', 'Reports', 'Audit log'] as const;
type Tab = typeof tabs[number];

export default function AdminMarketplaceControlCenter() {
  const [state, setState] = useState<State>(blank);
  const [tab, setTab] = useState<Tab>('Overview');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const res = await fetch('/api/admin/marketplace-control', { cache: 'no-store' });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'Could not load marketplace controls.');
    setState(data as State);
  }, []);
  useEffect(() => { void Promise.resolve().then(load).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not load marketplace controls.')); }, [load]);
  const save = async (action: string, data: Record<string, unknown>) => {
    setBusy(true); setError('');
    try { const res = await fetch('/api/admin/marketplace-control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...data }) }); const result = await res.json(); if (!res.ok) throw new Error(result.error || 'Could not save changes.'); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not save changes.'); }
    finally { setBusy(false); }
  };
  const catalogForm = (kind: string, title: string, items: Row[], extra: (item?: Row) => React.ReactNode = () => null) => <section className="space-y-3"><h2 className="text-lg font-bold">{title}</h2><CatalogEditor kind={kind} items={items} busy={busy} save={save} extra={extra}/></section>;
  const a = state.analytics;
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Phase 6 · Marketplace operations</p><h1 className="mt-1 text-3xl font-black">Admin control center</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Manage marketplace setup, seller verification, reports, and operational health.</p></div><nav className="flex flex-wrap gap-2" aria-label="Marketplace administration links"><a className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold" href="/admin/sellers">Seller accounts</a><a className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold" href="/admin/subscriptions">Plans & payments</a><a className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold" href="/admin/product-moderation">Product approvals</a></nav></header>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="Marketplace control sections">{tabs.map((name) => <button key={name} onClick={() => setTab(name)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${tab === name ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-100'}`}>{name}</button>)}</nav>
    {tab === 'Overview' && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Seller accounts', a.sellers], ['Seller products', a.products], ['Subscription plans', a.plans], ['Subscriptions', a.subscriptions], ['Payment submissions', a.payments], ['Reports', a.reports], ['Pending reports', a.pendingReports], ['Verification records', a.verifications]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-500">{String(label)}</p><p className="mt-1 text-2xl font-black">{String(value ?? '—')}</p></article>)}</div><div className="grid gap-4 lg:grid-cols-2"><Summary title="Product approval status" value={a.productsByStatus}/><Summary title="Payment status" value={a.paymentsByStatus}/></div><p className="text-xs text-slate-500">Analytics are current database totals. The overview does not claim revenue reconciliation or provider-verified payment status.</p></>}
    {tab === 'Categories' && catalogForm('categories', 'Marketplace categories', state.catalog.categories)}
    {tab === 'Subcategories' && catalogForm('subcategories', 'Marketplace subcategories', state.catalog.subcategories, () => <SelectField name="category_id" label="Parent category" rows={state.catalog.categories}/>)}
    {tab === 'Conditions' && catalogForm('conditions', 'Product conditions', state.catalog.conditions)}
    {tab === 'Attributes' && <div className="space-y-8">{catalogForm('attributes', 'Dynamic attributes', state.catalog.attributes, () => <><SelectField name="category_id" label="Category (optional)" rows={state.catalog.categories} optional/><SelectField name="subcategory_id" label="Subcategory (optional)" rows={state.catalog.subcategories} optional/><SelectField name="product_condition_id" label="Condition (optional)" rows={state.catalog.conditions} optional/><label className="text-xs font-semibold">Input type<select name="input_type" defaultValue="text" className="mt-1 block w-full rounded-lg border p-2 text-sm"><option>text</option><option>number</option><option>boolean</option><option>select</option><option>multiselect</option></select></label><label className="text-xs"><input name="is_required" type="checkbox"/> Required</label><label className="text-xs">Validation rules JSON<input name="validation_rules" defaultValue="{}" className="mt-1 block w-full rounded-lg border p-2 font-mono text-xs"/></label></>)}{catalogForm('options', 'Attribute options', state.catalog.options, () => <><SelectField name="attribute_id" label="Attribute" rows={state.catalog.attributes}/><p className="text-xs text-slate-500">Options apply to select and multiselect attributes.</p></>)}</div>}
    {tab === 'Verifications' && <section className="space-y-3"><h2 className="text-lg font-bold">Seller verification review</h2>{state.verifications.map((v) => <VerificationCard key={v.id} row={v} busy={busy} save={save}/>)}{!state.verifications.length && <Empty/>}</section>}
    {tab === 'Reports' && <section className="space-y-3"><h2 className="text-lg font-bold">Marketplace reports</h2>{state.reports.map((r) => <ReportCard key={r.id} row={r} busy={busy} save={save}/>)}{!state.reports.length && <Empty/>}</section>}
    {tab === 'Audit log' && <section className="space-y-3"><h2 className="text-lg font-bold">Recent admin activity</h2>{state.audit.map((event) => <article key={event.id} className="rounded-xl border bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-2"><strong>{String(event.action)}</strong><time className="text-xs text-slate-500">{new Date(String(event.created_at)).toLocaleString()}</time></div><p className="mt-1 text-xs text-slate-600">{String(event.actor)} · {String(event.resource_type)} · {String(event.resource_id)}</p><pre className="mt-2 overflow-auto text-xs text-slate-500">{JSON.stringify(event.metadata || {})}</pre></article>)}{!state.audit.length && <Empty/>}</section>}
  </main>;
}

function CatalogEditor({ kind, items, busy, save, extra }: { kind: string; items: Row[]; busy: boolean; save: (action: string, data: Record<string, unknown>) => Promise<void>; extra: (item?: Row) => React.ReactNode }) {
  const fields = kind === 'attributes' ? ['name', 'attribute_key'] : kind === 'options' ? ['value', 'label'] : ['name', 'slug', 'description'];
  const submit = (event: React.FormEvent<HTMLFormElement>, id?: string) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const values: Record<string, unknown> = {}; for (const key of fields) values[key] = fd.get(key); if (fd.has('is_active')) values.is_active = fd.get('is_active') === 'on'; if (kind === 'attributes') { values.input_type = fd.get('input_type'); values.is_required = fd.get('is_required') === 'on'; try { values.validation_rules = JSON.parse(String(fd.get('validation_rules') || '{}')); } catch { return; } } if (kind === 'subcategories' || kind === 'attributes') { for (const key of ['category_id', 'subcategory_id', 'product_condition_id']) if (fd.has(key)) values[key] = fd.get(key) || null; } if (kind === 'options' && fd.has('attribute_id')) values.attribute_id = fd.get('attribute_id'); void save('save_catalog', { kind, id, values }); };
  return <><form onSubmit={(e) => submit(e)} className="grid gap-2 rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-3">{fields.map((field) => <input key={field} required={field !== 'description'} name={field} placeholder={field.replace('_', ' ')} maxLength={field === 'description' ? 1000 : 160} className="rounded-lg border p-2 text-sm dark:bg-slate-950"/>)}{extra()}<button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Add item</button></form>{items.map((item) => <form key={item.id} onSubmit={(e) => submit(e, item.id)} className="grid gap-2 rounded-xl border bg-white p-3 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-4">{fields.map((field) => <input key={field} name={field} aria-label={field} defaultValue={String(item[field] ?? '')} className="min-w-0 rounded-lg border p-2 text-xs dark:bg-slate-950"/>)}{kind === 'attributes' && <><select name="input_type" defaultValue={String(item.input_type)} className="rounded-lg border p-2 text-xs"><option>text</option><option>number</option><option>boolean</option><option>select</option><option>multiselect</option></select><label className="text-xs"><input name="is_required" type="checkbox" defaultChecked={Boolean(item.is_required)}/> Required</label><input name="validation_rules" defaultValue={JSON.stringify(item.validation_rules || {})} className="rounded-lg border p-2 font-mono text-xs"/></>}{(kind === 'subcategories' || kind === 'attributes') && <><SelectField name="category_id" label="Category" rows={blank.catalog.categories} initial={String(item.category_id || '')} optional/><SelectField name="subcategory_id" label="Subcategory" rows={blank.catalog.subcategories} initial={String(item.subcategory_id || '')} optional/><SelectField name="product_condition_id" label="Condition" rows={blank.catalog.conditions} initial={String(item.product_condition_id || '')} optional/></>}{kind === 'options' && <input type="hidden" name="attribute_id" value={String(item.attribute_id)}/>}<label className="text-xs"><input name="is_active" type="checkbox" defaultChecked={Boolean(item.is_active)}/> Active</label><button disabled={busy} className="rounded-lg border px-3 py-2 text-xs font-bold">Save / update</button></form>)}</>;
}
function SelectField({ name, label, rows, initial = '', optional = false }: { name: string; label: string; rows: Row[]; initial?: string; optional?: boolean }) { return <label className="text-xs font-semibold">{label}<select required={!optional} name={name} defaultValue={initial} className="mt-1 block w-full rounded-lg border p-2 text-sm dark:bg-slate-950"><option value="">{optional ? 'Any' : 'Select…'}</option>{rows.map((r) => <option key={r.id} value={r.id}>{String(r.name || r.label || r.attribute_key)}</option>)}</select></label>; }
function VerificationCard({ row, busy, save }: { row: Row; busy: boolean; save: (a: string, d: Record<string, unknown>) => Promise<void> }) { return <article className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><strong>{String((row.seller as Row | undefined)?.display_name || 'Seller')}</strong><p className="text-xs text-slate-500">{String((row.seller as Row | undefined)?.university || '')} · Current: {String(row.status)}</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void save('review_verification', { id: row.id, status: f.get('status'), level: f.get('level'), label: f.get('label'), notes: f.get('notes') }); }} className="mt-3 grid gap-2 sm:grid-cols-4"><select name="status" defaultValue={String(row.status)} className="rounded-lg border p-2 text-sm"><option>unverified</option><option>verified</option><option>rejected</option><option>suspended</option></select><input name="level" defaultValue={String(row.verification_level)} placeholder="Verification level" className="rounded-lg border p-2 text-sm"/><input name="label" defaultValue={String(row.public_label || '')} placeholder="Public badge label" className="rounded-lg border p-2 text-sm"/><input name="notes" defaultValue={String(row.notes || '')} placeholder="Review note" className="rounded-lg border p-2 text-sm"/><button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Save review</button></form></article>; }
function ReportCard({ row, busy, save }: { row: Row; busy: boolean; save: (a: string, d: Record<string, unknown>) => Promise<void> }) { return <article className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-2"><strong>{String(row.reason)}</strong><span className="text-xs capitalize">{String(row.status)}</span></div><p className="mt-1 text-sm">{String(row.details || 'No details supplied')}</p><p className="mt-1 text-xs text-slate-500">{String((row.product as Row | undefined)?.name || (row.seller as Row | undefined)?.display_name || 'Marketplace item')} · {new Date(String(row.created_at)).toLocaleString()}</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void save('review_report', { id: row.id, status: f.get('status'), notes: f.get('notes') }); }} className="mt-3 flex flex-wrap gap-2"><select name="status" defaultValue={String(row.status)} className="rounded-lg border p-2 text-xs"><option>reviewing</option><option>resolved</option><option>dismissed</option></select><input name="notes" defaultValue={String(row.review_notes || '')} placeholder="Review note" className="min-w-48 flex-1 rounded-lg border p-2 text-xs"/><button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Save</button></form></article>; }
function Summary({ title, value }: { title: string; value: unknown }) { const entries = value && typeof value === 'object' ? Object.entries(value as Record<string, number>) : []; return <article className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">{title}</h2>{entries.map(([key, count]) => <p key={key} className="mt-2 flex justify-between text-sm capitalize"><span>{key.replaceAll('_', ' ')}</span><strong>{count}</strong></p>)}</article>; }
function Empty() { return <p className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Nothing to review.</p>; }
