'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { formatTZS } from '@/lib/mockData';

type Campaign = { id: string; name: string; price: number; sellerName: string; commissionRate: number; shareUrl: string };
type Commission = { id: string; product_title: string; amount: number; status: string; created_at: string };
type Data = { campaigns: Campaign[]; commissions: Commission[]; earnings: { total: number; payable: number; pending: number; paid: number }; error?: string };

export default function WingaMarketplaceEarnings() {
  const [data, setData] = useState<Data | null>(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { const response = await fetch('/api/winga/campaigns', { cache: 'no-store' }); const result = await response.json() as Data; if (!response.ok) throw new Error(result.error || 'Could not load campaigns.'); setData(result); }, []);
  useEffect(() => { void Promise.resolve().then(load).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load earnings.')); }, [load]);
  if (!data && !error) return <section className="mt-6 rounded-2xl border bg-white p-5 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900">Loading promotion campaigns and earnings…</section>;
  return <section className="mt-6 space-y-4"><article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 dark:border-emerald-900 dark:bg-emerald-950/30"><h2 className="font-bold text-emerald-950 dark:text-emerald-100">Winga earnings</h2><p className="mt-1 text-xs text-emerald-900/80 dark:text-emerald-100/80">UniSoko product commissions and seller-funded promotion commissions are recorded after the order is paid and delivered.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[['Payable', data?.earnings.payable], ['Pending review', data?.earnings.pending], ['Paid', data?.earnings.paid], ['Lifetime', data?.earnings.total]].map(([label, amount]) => <div key={String(label)} className="rounded-xl bg-white/80 p-3 dark:bg-slate-900"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-1 text-sm font-black">{formatTZS(Number(amount || 0))}</p></div>)}</div></article>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-bold">Seller promotion campaigns</h2><p className="mt-1 text-xs text-slate-500">Share a product link; your Winga code is carried to checkout. You earn the rate each seller selected.</p></div><Link href="/" className="text-xs font-bold text-indigo-600">Browse UniSoko products</Link></div>{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{data?.campaigns.length ? <div className="mt-4 divide-y dark:divide-slate-800">{data.campaigns.map((campaign) => <article key={campaign.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold">{campaign.name}</p><p className="text-xs text-slate-500">{campaign.sellerName} · {formatTZS(campaign.price)} · {campaign.commissionRate * 100}% commission</p></div><a href={campaign.shareUrl} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Open share link</a></article>)}</div> : <p className="mt-4 text-sm text-slate-500">No seller campaigns are currently open. Your Winga code can still earn commissions on eligible UniSoko products.</p>}</article>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Commission activity</h2>{data?.commissions.length ? <div className="mt-3 divide-y dark:divide-slate-800">{data.commissions.map((row) => <div key={row.id} className="flex flex-wrap justify-between gap-2 py-2 text-sm"><span>{row.product_title} <span className="ml-1 text-xs capitalize text-slate-500">· {row.status}</span></span><strong>{formatTZS(Number(row.amount))}</strong></div>)}</div> : <p className="mt-2 text-sm text-slate-500">Commissions appear after a referred order is paid and marked delivered.</p>}</article></section>;
}
